apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 3.6.0
    replicas: {{ .Values.cluster.kafka.replicas }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
    storage:
      type: {{ .Values.cluster.storage }}
  zookeeper:
    replicas: {{ .Values.cluster.zookeeper.replicas }}
    storage:
      type: {{ .Values.cluster.storage }}
  entityOperator:
    topicOperator: {}
    userOperator: {}