{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ . }}
  labels:
    strimzi.io/cluster: coinbase-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000  # 2 hrs
    segment.bytes: 1073741824
---
{{- end }}