producer:
  # -- name of deployment in k8s
  deploymentName: coinbase-producer-deployment
  # -- name of service in k8s
  serviceName: coinbase-producer-service
  # -- app name linking deployment and service
  appName: coinbase-producer
  # -- deployment image
  image: coinbase-producer:latest  # default overwritten by gh-actions
  # -- image pull policy
  imagePullPolicy: IfNotPresent
  # -- replicas for deployment
  replicas: 1
kafka:
  # -- namespace where kafka is deployed
  clusterNamespace: "dev"
  # -- name of the kafka cluster
  clusterName: "coinbase-kafka"
  # -- address of the kafka cluster
  address: "coinbase-kafka-kafka-bootstrap.dev.svc.cluster.local:9092"
  # -- the topic to forward data to
  topic: "ticker"