apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.producer.deploymentName }}
spec:
  replicas: {{ .Values.producer.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.producer.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.producer.appName }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      initContainers:
        - name: wait-for-kafka  # avoids race condition for kafka cluster setup
          image: bitnami/kubectl:latest
          imagePullPolicy: Always
          command: 
            - /bin/bash
            - -c
            - |
              kubectl wait kafka/$KAFKA_CLUSTER_NAME --for=condition=Ready --timeout=300s -n $KAFKA_CLUSTER_NAMESPACE
          env:
            - name: KAFKA_CLUSTER_NAMESPACE
              value: {{ .Values.kafka.clusterNamespace }}
            - name: KAFKA_CLUSTER_NAME
              value: {{ .Values.kafka.clusterName }}
      containers:
        - name: {{ .Values.producer.appName }}
          image: {{ .Values.producer.image }}
          imagePullPolicy: {{ .Values.producer.imagePullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_ADDRESS
              value: {{ .Values.kafka.address }}
            - name: KAFKA_TOPIC
              value: {{ .Values.kafka.topic }}
