apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.producer.serviceName }}
spec:
  # type: LoadBalancer
  selector:
    app: {{ .Values.producer.appName }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000