name: "pull-request"

on:
  pull_request:
    branches:
      - "main"

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Formatting Checks
        run: |
          make test_format

      - name: Unit Tests
        run: |
          make test_unit

      - name: Setup Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: github-cluster

      - name: Integration Tests
        run: |
          make docker-build
          kind load docker-image coinbase-connector --name github-cluster
          make test_integration
